version: 2.1
executors:
  default:
    docker:
      - image: ruby:3.1.2

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            gem install bundler
            bundle install
      - run:
          name: production
          command: |
            bundle exec rake db:setup RAILS_ENV=production
            bundle exec rspec