version: '3.8'
services:
  db:
    image: postgres:latest
#    container_name: myapp-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5552:5433"
  web:
    build: .
#    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_URL-postgres: //postgres:password@db:5433/postgres
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: {}



#version: '3.8'
#volumes:
#  db-data:
#    external: false
#
#services:
#  #  cache:
#  #    image: memcached:1.4-alpine
#
#  db:
#    environment:
#      POSTGRES_USER:
#      POSTGRES_PASSWORD:
#    image: postgres:15.2
#    ports:
#      - "5552:5432"
#    volumes:
#      - db-data:/usr/local/pgsql/data
#
#
#  #  jobs:
#  #    env_file: .env
#  #    build: .
#  #    volumes:
#  #      - .:/usr/src/app
#  #    command: bundle exec rake jobs:work
#  #    depends_on:
#  #      - db
#
#  app:
#    env_file: .env
#    build: .
#    volumes:
#      - .:/usr/src/app
#    ports:
#      - "3000:3000"
#    depends_on:
#      - db
#    environment:
#      - DATABASE_URL-postgres://postgres:password@db:5432/content_reels
#version: '3.8'
#services:
#  db:
#    image: postgres
#    ports:
#      - "8001:5432"
#
##  redis:
##    image: redis
##    ports:
##      - "6379:6379"
#  web:
#    build: .
#    ports:
#      - "3000:3000"
#    depends_on:
#      - db
##    environment:
##      - DATABASE_URL-postgres://postgres:password@db:5432/content_reels
###      - REDIS_URL-redis://redis:6379
#    volumes:
#      - .:/app
#volumes:
#  db_data: